### ISSUE TITLE
Disable interactive zoom

### ISSUE THREAD

**Issue by markusschanta** [altair-viz/altair_pandas#35]
Hi! First of all, this is a really great package and I use it a lot! It would be great if there was a way to disable the default interactive zoom on charts.

I use the charts on pages that need to be scrolled and when the cursor is over a chart, the interactive zoom magnifies the chart instead of scrolling the page. Had a look at the code and it seems there is no flag or other mechanism to make the [call to interactive()](https://github.com/altair-viz/altair_pandas/blob/ff83a5d7ebcf908f995682c14c5c93e26b397015/altair_pandas/_core.py#L205) optional. Alternatively, I can't figure out how to remove this from a chart object after a call to pandas' .plot(). Either of these would be very helpful! 

Thanks!

**Comment by jakevdp** [comment]
Zoom is not enabled by default; you must call `.interactive()` or manually define a scale-bound selection to add zoom to a chart. If you don't want zoom behavior, you can leave these out of the chart definition. See [Interval Selections](https://altair-viz.github.io/user_guide/interactions.html#interval-selections) for more information.

**Comment by markusschanta** [comment]
Thank you for your answer!

Agree that when I generate the Altair definition by manually, there is no zoom by default:

```import altair as alt
import pandas as pd

source = pd.DataFrame({
    'a': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
    'b': [28, 55, 43, 91, 81, 53, 19, 87, 52]
})

alt.Chart(source).mark_bar().encode(
    x='a',
    y='b'
)
```

When I simply do `source.plot()`, the resulting chart is zoomable by default. (NB: `source.plot()` producing an Altair chart requires `pd.set_option('plotting.backend', 'altair')` to be called beforehand; at least that's how I get it to do so.)

**Comment by jakevdp** [comment]
Oh, it sounds like you're talking about the [altair_pandas](https://github.com/altair-viz/altair_pandas) package then?

**Comment by markusschanta** [comment]
Yep, yep. For a second you had me worried I opened the issue on the wrong package. 😁

**Comment by markusschanta** [comment]
Hi @jakevdp! Any quick ideas on how to remove the ```interactive()``` zoom after creating a plot via ```source.plot()```/altair_pandas?

**Comment by jakevdp** [comment]
You can write `chart.selection = alt.Undefined` to remove all selections from an Altair chart.

**Comment by markusschanta** [comment]
Awesome, many thanks! I tried things like ```chart.selection = None``` and was also looking for a ```chart.remove_selection()``` or similar.

Whenever I want a chart to be very polished, a "proper" manually generated Altair is the way to go. For most cases, however, I quite like the quick & dirty way to plot a DataFrame that ```source.plot()``` provides.
